@url = http://localhost:3000

### Create Carrier
# @name carrier_create
POST {{url}}/carriers
Content-Type: application/json

{
    "name": "Carrier Create GSM",
    "email":   ["gsilvamedeiros@gmail.com"],
	"phone":   "21 97455-8555",
	"contact": "John Doe"
}

###
@carrier_id = {{carrier_create.response.body.id}}

### Get All Carrier
GET {{url}}/carriers

### Get By ID Carrier
GET {{url}}/carriers/{{carrier_id}}

### Get By ID Carrier - Test Not Found
GET {{url}}/carriers/d2aa190qfcbimq75qoaw

### Update Carrier
PATCH {{url}}/carriers/{{carrier_id}}
Content-Type: application/json

{
    "name": "Carrier LTDA - Name",
	"phone":   "21 97455-8500",
	"contact": "John Doe Name"
}

### Delete Carrier
DELETE {{url}}/carriers/{{carrier_id}}
