@url = http://localhost:3000

### Create Order
# @name order_create
POST {{url}}/orders
Content-Type: application/json

{
    "clientId": "d2aa160qfcbimq75qo8g",
    "addressId": "d2aa160qfcbimq75qo80",
	"products": [
		{
		    "productId": "d2aa0u0qfcbimq75qo70",
		    "quantity": 1,
		    "price": 19.99
		},
		{
		    "productId": "d2aa0ogqfcbimq75qo6g",
		    "quantity": 1,
		    "price": 21.99
		}
	]
}

###
@order_id = {{order_create.response.body.id}}

### Get All Order
GET {{url}}/orders

### Get By ID Order
GET {{url}}/orders/{{order_id}}

### Get By ID Order - Test Bot Found
GET {{url}}/orders/d2aa2fgqfcbimq75qod0

### Update Order
PATCH {{url}}/orders/{{order_id}}
Content-Type: application/json

{
    "clientId": "",
    "addressId": "",
}

### Update Carrier Order
PATCH {{url}}/orders/carrier/{{order_id}}
Content-Type: application/json

{
    "carrierId": ""
}

### Delete Order
DELETE {{url}}/orders/{{order_id}}
