@url = http://localhost:3000

### Create Order
# @name order_create
POST {{url}}/orders
Content-Type: application/json

{
    "clientId": "",
    "addressId": "",
	"products": [
		{
		    "productId": "",
		    "quantity": 1,
		    "price": 99.99
		},
	    {
		    "productId": "",
		    "quantity": 1,
		    "price": 99.99
		}
	]
}

###
@order_id = {{order_create.response.body.id}}

### Get All Order
GET {{url}}/orders

### Get By ID Order
GET {{url}}/orders/{{order_id}}

### Update Order
PATCH {{url}}/orders/{{order_id}}
Content-Type: application/json

{
    "clientId": "",
    "addressId": "",
}

### Delete Order
DELETE {{url}}/orders/{{order_id}}
