@url = http://localhost:3000

### Create Order
# @name order_create
POST {{url}}/orders
Content-Type: application/json

{
    "clientId": "d29lk08qfcbmfu3it4s0",
    "addressId": "d29lk08qfcbmfu3it4rg",
	"products": [
		{
		    "productId": "d29lk38qfcbmfu3it4sg",
		    "quantity": 1,
		    "price": 19.99
		}
	]
}

###
@order_id = {{order_create.response.body.id}}

### Get All Order
GET {{url}}/orders

### Get By ID Order
GET {{url}}/orders/{{order_id}}

### Update Order
PATCH {{url}}/orders/{{order_id}}
Content-Type: application/json

{
    "clientId": "",
    "addressId": "",
}

### Update Carrier Order
PATCH {{url}}/orders/carrier/{{order_id}}
Content-Type: application/json

{
    "carrierId": ""
}

### Delete Order
DELETE {{url}}/orders/{{order_id}}
