### Create Carrier

POST http://localhost:3000/carriers
Content-Type: application/json

{
    "name": "Carrier Name",
    "email":   ["test@company.com"],
	"phone":   "21 974558555",
	"contact": "John Doe"
}

### Get All Carrier
GET http://localhost:3000/carriers

### Get By ID Carrier
GET http://localhost:3000/carriers/:id